"""sdffggf

Revision ID: 0b341e472fdd
Revises: 653e11cd2983
Create Date: 2021-10-23 17:48:09.637201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b341e472fdd'
down_revision = '653e11cd2983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_BookwithUser_user_email', table_name='BookwithUser')
    op.drop_column('BookwithUser', 'user_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BookwithUser', sa.Column('user_email', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.create_index('ix_BookwithUser_user_email', 'BookwithUser', ['user_email'], unique=False)
    # ### end Alembic commands ###
